### ISSUE TITLE
Instructions unclear

### ISSUE THREAD

**Issue by Dermiste** [usineur/hode#11]
Hi there,

I am trying to figure out what exactly I need to make this work, in my SD card I should see (inside "hode" folder, which is inside "switch" folder, which is at the root):
- hode.nro
- hode.ini
- hod.paf from ISO found at https://www.myabandonware.com/game/heart-of-darkness-a4h#download CD
- setup.dat from RIP found at same address
- all other files found inside the RIP

Note that setup.dat is not at the root but inside a "setup" folder, should it be moved inside "hode" folder?
How do I start the game from my switch? Will it show on the main menu along with the other games?

Thanks in advance :)

**Comment by usineur** [comment]
> Hi there,
> 
> I am trying to figure out what exactly I need to make this work, in my SD card I should see (inside "hode" folder, which is inside "switch" folder, which is at the root):

This is correct
> 
> * hode.nro
> * hode.ini
> * hod.paf from ISO found at https://www.myabandonware.com/game/heart-of-darkness-a4h#download CD
> * setup.dat from RIP found at same address
> * all other files found inside the RIP
> 

The following datafiles must be placed in the "hode" folder:

- dark_hod.lvl
- dark_hod.mst
- dark_hod.sss
- fort_hod.lvl
- fort_hod.mst
- fort_hod.sss
- hod.paf
- isld_hod.lvl
- isld_hod.mst
- isld_hod.sss
- lar1_hod.lvl
- lar1_hod.mst
- lar1_hod.sss
- lar2_hod.lvl
- lar2_hod.mst
- lar2_hod.sss
- lava_hod.lvl
- lava_hod.mst
- lava_hod.sss
- pwr1_hod.lvl
- pwr1_hod.mst
- pwr1_hod.sss
- pwr2_hod.lvl
- pwr2_hod.mst
- pwr2_hod.sss
- rock_hod.lvl
- rock_hod.mst
- rock_hod.sss
- setup.dat

> Note that setup.dat is not at the root but inside a "setup" folder, should it be moved inside "hode" folder?

Yes.

> How do I start the game from my switch? Will it show on the main menu along with the other games?

As any other homebrew, via HBMenu. Btw that's a weird question, is your Switch cracked ?

**Comment by Dermiste** [comment]
My Switch is not cracked, I just tried this evening to make this build for the first time so I'm rather new to this.
In the end all that was missing is setup at the right location and HBMenu ready upfront before that, correct?

**Comment by usineur** [comment]
Yes.
