### ISSUE TITLE
Not playable on Vita

### ISSUE THREAD

**Issue by fuckgithub668** [usineur/hode#2]
I can't control my character on Vita, based on the instructions in the README.txt.  The buttons work correctly, but the dpad/analog stick are not reliable.  Sometimes they work and sometimes they don't.  I'm not sure why.

**Comment by usineur** [comment]
Welp, no idea. Buttons always work for me.

**Comment by usineur** [comment]
Ok, I was able to reproduce this problem. It happens after any use of the left analog stick. I will try to fix this problem later tonight.

**Comment by usineur** [comment]
You could try this [eboot.bin](https://www.ferb.fr/vita/eboot.bin) ?

**Comment by fuckgithub668** [comment]
That seems to have fixed the problem, thank you!
