### ISSUE TITLE
Hidden DAT files

### ISSUE THREAD

**Issue by xadox-1st** [usineur/hode#3]
It was a bit tricky to find the dat files on the cd.

After searching for a while I was able to find them in the HeartOfDarkness_XX.exe.
Maybe you could add the info to the readme, that most of the files have to be extracted from the exe.

**Comment by usineur** [comment]
What is that ? On the CD version i own, there is no trace of a HeartOfDarkness_XX.exe.

You just need to install the game and copy all needed files, and copy hod.paf on the CD itself (this file is not copied on the hd)
