### ISSUE TITLE
Switch: Can't start level two

### ISSUE THREAD

**Issue by xadox-1st** [usineur/hode#4]
I use version 0.2.6 on the switch with DAT files from a German CD.

After level 1 is finished, the movie sequence starts and I start again shortly before reaching the top of the mountain (a section before the closing dinosaur head).

**Comment by usineur** [comment]
Currently, it seems that only English and French versions are fully supported.

An other user reported me a similar case on Spanish version
https://twitter.com/9esferas_/status/1188914295079428096

**Comment by xadox-1st** [comment]
Thx for the response.

**Comment by xadox-1st** [comment]
I now use an english version of the game.
But I still have the same problem, that after finishing the first level and the movie sequence I have to continue at the last checkpoint of the first level again.

The hash values of most files match those of RELEASES.yaml.
Only the **setup.dat** and **hod.paf** have different values.

`e7c188e5c47632d512d96d9da89fc8c060528d45 *DARK_HOD.LVL
6c2d93b2e31c299215d0fdf05ac1e8e8e95e9042 *DARK_HOD.MST
8d5b19842e551b8ec73bda411c210cc96e08569a *DARK_HOD.SSS
82456ed6e29780b5b8031a67ba3dddb8da813c19 *FORT_HOD.LVL
ce55095902ade9f1d8a198f271d0946d6228b90d *FORT_HOD.MST
6ff572b553d93040c9cad74891db05b2cc8267c6 *FORT_HOD.SSS
bb3e556a5bd134597ef2146f9890643a9bb11256 *hod.paf
f78e9316f2187c0ca9e42abe8a2242b3d3e6feaf *ISLD_HOD.LVL
448e5dd5bbe59621279562d8695c9a864cb4c286 *ISLD_HOD.MST
61c5da6dfcf80684c56baebddb04125ca0c1f209 *ISLD_HOD.SSS
84f7b33a9b57f2afa68063e0128512991f86dfa0 *LAR1_HOD.LVL
9db53a4a75327eeca45ffa5b761a9f04af5e5204 *LAR1_HOD.MST
72667991fde3caf36978da1fa929695de80abe4b *LAR1_HOD.SSS
999b2548490f586f955c9f5c6db95f88d49102f3 *LAR2_HOD.LVL
333ea4e6be6ca9aad735fafe59177546aab41c4e *LAR2_HOD.MST
c5c655b718ead1d2eb460a058df7eb3b795dea9e *LAR2_HOD.SSS
2921eb2f78354e79c1257ef55543bb1a1492e914 *LAVA_HOD.LVL
c05ce42c0abdbb2dbfc109cbb4ea7eee1937445d *LAVA_HOD.MST
8fc8d2c86f67e13ca840d604c603249b20723f85 *LAVA_HOD.SSS
cd6489e11914770d95034aa6afaa2fc67f035ce8 *PWR1_HOD.LVL
f821e5686ae27b2ed5000ea4b38a464ecebe44a7 *PWR1_HOD.MST
cbb39e1bfd24dcbd5bf65f9e0b92faaa9b6b02a6 *PWR1_HOD.SSS
7263ecf8d51d45c2c62dc11701eac03b67738fd8 *PWR2_HOD.LVL
132b29e758a28529009e979ef31a29a42d0a5c4b *PWR2_HOD.MST
24342241b4353777cc22696be8a684d635f9c809 *PWR2_HOD.SSS
cdb3d7ad1ae13f2234380f79bc8ec57e1e505cef *ROCK_HOD.LVL
5b49637348f6c6a2737a64cacf01f9bcef8e83f6 *ROCK_HOD.MST
55c841f6c091c2ae68f0636c075c66405d00cc6a *ROCK_HOD.SSS
56fd54d28074657b947e165134f044d9a91cef47 *SETUP.DAT
`

**Comment by usineur** [comment]
Well, did you restart with a fresh "setup.cfg" ? If no, retry without this file at "first launch"

If it doesn't help, I can't help you that much. Try to see with the author of the engine.

**Comment by xadox-1st** [comment]
Yes I already tried with a fresh one.
With the Win32 version of HODE it works as it should with my german and english version.
So there has to be some difference with the switch release.

**Comment by usineur** [comment]
Ok I see the problem now. My bad, some confusion which an other old bug.

I wonder how it can work for the win32 version. Here, on my linux own built, it doesn't (based on 0.2.6 sources)

The "load/save" routine has changed. Now it only saves when you finish a level, and it reload the last checkpoint based on the previous level before he level num increments.
That's why the problem exists also on Switch and Vita ports. Maybe the win32 version was built with no exactly the 0.2.6 sources, dunno, but that's weird.

I will try to fix that this week-end. For now, i suggess you to play with 0.2.5 version.

**Comment by xadox-1st** [comment]
Thanks for finding the problem.

**Comment by usineur** [comment]
Ok, there was also an error on my side that cause the save to never be reloaded.

Should be fixed. Could you please try this [nro](https://www.ferb.fr/switch/hode.nro) ?

**Comment by xadox-1st** [comment]
Ok I can enter Level 2 now.
But somehow the save and loading is not working proberly (Same problem in 0.2.6, also).
I played until Level 2 and exited the game throught the menu.
If I start the NRO again I can see my progress under choose player, but If I am trying to continue I am starting in Level 1 again.

**Comment by usineur** [comment]
I have updated the link above. Please retry with this one.

**Comment by xadox-1st** [comment]
Stil the same save and load problem.

**Comment by usineur** [comment]
0.2.7 release is out. Can you retry with this version ? I have performed quick tests, it seems ok to me.

**Comment by xadox-1st** [comment]
Now the problem ist back that I cant enter Level 2.

**Comment by usineur** [comment]
Well, I just retry on PC, Switch and Vita (0.2.7), I'm able to full complete the level 1 and enter level 2 with no problem.

**Comment by xadox-1st** [comment]
Hmm... On the PC version its working for me, too.
Think I will play it on pc then.

**Comment by usineur** [comment]
Ok, I will keep this issue open in case someone else reports the same problem.

**Comment by usineur** [comment]
0.2.8 is out if you want to have a new try.
