### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by neuromancer** [usineur/hode#5]
Hi,

I'm following this neat re-implementation engine. The screenshots look great so far, but it is a little unclear from the README what elements from gameplay are implemented and if the game is completable or not. Can you add a few lines in the README on what to expect if you want to test this engine?

Thanks!

**Comment by usineur** [comment]
The README comes from the original engine. Please note that this repo is dedicated to my Vita and Switch ports. I'm not working myself of the engine.

To what I know:
- French and English should be completable with few glitches. An user on twitter reports me for example that Spanish version crashes during a cutscene.
- Menu is still WIP
- PSX assets support are WIP too

**Comment by neuromancer** [comment]
Too bad @cyxx does not maintain a public repository of hode in Github. Thanks for the clarification.

**Comment by cyxx** [comment]
I will try to improve the README, but as of 0.2.5 the game is completable (did a playthrough with French datafiles).
The problem with the Italian PAF animation in level 2 has been fixed yesterday, and will be integrated in the next build.
