### ISSUE TITLE
movie sound assertion

### ISSUE THREAD

**Issue by Cowcat5150** [usineur/hode#9]
Crash in menu playing movies:

hode: menu.cpp:330: int Menu::getSoundNum(int, int) const: Assertion `index < count' failed.
abort

Compiled and tested on Debian X86_64 and Amiga Classic PPC (SDL1 fork).

**Comment by usineur** [comment]
Fixed. 96b1674a6d81854c528e58cf66e62b034e876565

**Comment by usineur** [comment]
Should be fixed now

**Comment by Cowcat5150** [comment]
Nice. Works now :) Good job.
